# Generated by Django 4.2.5 on 2023-11-24 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_tag_project_vote_total_project_vote_ratio_review_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='source_Link',
            new_name='source_link',
        ),
    ]
